### ISSUE TITLE
The sound is not working

### ISSUE THREAD

**Issue by vSleichert** [yutasuzuki/react-native-record-screen#1]
Hey, 

I am trying to implement this in our project. The sound is not working though ( its commented out in /ios/RecordScreen.m ).
I also saw that there is few commits related to Android. How does it look like ? 

Thanks

**Comment by yutasuzuki** [comment]
@vSleichert 
Hi.
This is current status.

About iOS.
You can't record now, but I'll add a recording feature in the future.

About Android.
HBRecorder is now used to support recording and audio recording. But this one cannot be cropped.

I'd like to make iOS and Android compatible with the same functionality in the future. But it's hard to support it right away, so if you need it right away, please duplicate it and fix it.

Thanks.

**Comment by voslartomas** [comment]
@yutasuzuki Hi, we have taken your library and made it working for iOS and Android as well, you can take a look here https://github.com/beattv/react-native-screen-recorder, there is no cropping, so you might take our solution and apply to your library. Or feel free extend new library.

**Comment by yutasuzuki** [comment]
@voslartomas Sorry I'm late.
Thank you. I am going to use it as an example.

**Comment by yutasuzuki** [comment]
@voslartomas I replaced it because your code is good.
And I modified it so that the microphone can be switched.
Thank you.
