### ISSUE TITLE
Cropping

### ISSUE THREAD

**Issue by gut4** [yutasuzuki/react-native-record-screen#10]
What was the reason to remove cropping?
It looks like basic useful feature.

**Comment by yutasuzuki** [comment]
@gut4 
I want to keep simple area of ​​responsibility this module.

If you want to croping, using react-native-ffmpeg or iOS is AVMutableComposition and Android is MediaCodec.

I tried AVMutableComposition and MediaCodec.
AVMutableComposition was work. But MediaCodec is didn't work.
There were few crop samples using Mediacodec.(A lot of crop image)

This is demo using react-native-ffmpeg.
DEMO: [react-native-record-screen-zone](https://github.com/yutasuzuki/react-native-record-screen-zone)
