### ISSUE TITLE
Stop record Ios crash 

### ISSUE THREAD

**Issue by philip-bui-goldenowl** [yutasuzuki/react-native-record-screen#109]
I using version 0.51, ios 13.7, crash when i stop recording 
I using simulator 
<img width="756" alt="Screenshot 2023-06-26 at 2 28 01 PM" src="https://github.com/yutasuzuki/react-native-record-screen/assets/89563273/61761cd8-e56e-420d-a52a-451c68b9e3ef">

**Comment by yutasuzuki** [comment]
@philip-bui-goldenowl 
Hi!This doesn't work in the simulator.
