### ISSUE TITLE
Error cannot read property 'setup' of null 

### ISSUE THREAD

**Issue by Ashot1995** [yutasuzuki/react-native-record-screen#111]
Hi @yutasuzuki !
I  try connect in this package for IOS and have error 
Error cannot read property 'setup' of null 
<img width="988" alt="Screenshot 2023-07-28 at 17 55 53" src="https://github.com/yutasuzuki/react-native-record-screen/assets/29658245/7e024e2c-c6ae-450e-9f49-17b54294676d">
<img width="530" alt="Screenshot 2023-07-28 at 17 57 25" src="https://github.com/yutasuzuki/react-native-record-screen/assets/29658245/c31ba19f-83d9-4e7d-94a5-28e605a2a1c3">
<img width="664" alt="Screenshot 2023-07-28 at 17 57 37" src="https://github.com/yutasuzuki/react-native-record-screen/assets/29658245/895eadc8-a570-4220-9941-2634868dcd0f">

Can you help me ?
How to fix this error ?

**Comment by Ashot1995** [comment]
@Seachaos @yutasuzuki @345ml @robrechtme  Hi all Can we help me  fix that error?
Thanks

**Comment by yutasuzuki** [comment]
@Ashot1995 Hi! 
Maybe there is not Replaykit.
I don't remember ever setting it.

<img width="935" alt="replaykit" src="https://github.com/yutasuzuki/react-native-record-screen/assets/4530616/e3555d2f-53a5-4ffd-87eb-db1691d0552d">

I think it used to work without this setting.
Maybe it's just me...

If you can solve this problem, please let me know so I can write it in the README.

**Comment by Seachaos** [comment]
Hi, after you installed the package.
Did you build the binary?  ( from Xcode or some command like `yarn ios` )

**Comment by Ashot1995** [comment]
@yutasuzuki yes it helped me, you can add it to the readme file,
Thank you

**Comment by yutasuzuki** [comment]
@Seachaos Thanks for your reply.
Were you able to use react-native-record-screen@0.6.0 without adding ReplayKit.framework to Link Binary With Libraries?

**Comment by Seachaos** [comment]
> @Seachaos Thanks for your reply.
> Did you need to set up ReplayKit.framework before? (I don't recall doing so.)
> If you know, please tell me.

No, I don't need set up `ReplayKit.framework` to link binary
My iOS build is so far so good.

**Comment by yutasuzuki** [comment]
@Seachaos 
I tried with previous versions. It seems that ReplayKit.framework has been necessary since react-native-record-screen@0.6.0. It's likely that ReplayKit.framework became necessary when I implemented a feature to prevent the process from stopping in the background.

When I checked, I was troubleshooting, so I'm sure I had made this setting.
Thank you.

**Comment by robrechtme** [comment]
@Ashot1995 did you install pods?

```
npx pod-install
```

**Comment by Seachaos** [comment]
Hi @yutasuzuki 
I got time to test it with new project.
You are right.

I create new proejct, it's need `ReplayKit.framework`
Here is my steps:
- npx react-native init NewProject
- yarn add react-native-record-screen
- run: pod install
if no add `ReplayKit.framework` it's will failed.

**Comment by Ashot1995** [comment]
@robrechtme Yes, of course, as we already found out, the problem was for ReplayKit.framework

**Comment by Ashot1995** [comment]
everything is working now, thanks everyone

**Comment by 345ml** [comment]
Good job!
