### ISSUE TITLE
App Permissions minibug

### ISSUE THREAD

**Issue by cristea2017** [yutasuzuki/react-native-record-screen#13]
After installing this lib start recording doesn't working. This is caused because App permissions is off (microphone and storage).
Also when i started app for the first time request for permission doesn't appear.  is this a bug or a future :D ? 
Thanks  ;)

**Comment by yutasuzuki** [comment]
@cristea2017 Thanks!
It is a specification that does not provide permissions.
I figured that permissions would be shown at different times in different apps, so that's up to the developer. So I'll leave that to the developers.

**Comment by cristea2017** [comment]
ok
