### ISSUE TITLE
Automatically stop on Android

### ISSUE THREAD

**Issue by phithu** [yutasuzuki/react-native-record-screen#3]
Hi @yutasuzuki, Thank for create great lib.  I run example code on iOS working very well, but Android is automatically stop record screen
My environment:
Android version = 10.0
React Native = 0.63.2
buildToolsVersion = "29.0.2"
minSdkVersion = 26
compileSdkVersion = 29
targetSdkVersion = 29
googlePlayServicesAuthVersion = "17.0.0"

**EDIT**
Add code below in ``startRecording`` function it is working well
```kotlin
if(doesSupportEncoder("h264")){
      hbRecorder!!.setVideoEncoder("H264");
} else{
      hbRecorder!!.setVideoEncoder("DEFAULT");
}
```
https://github.com/HBiSoft/HBRecorder/issues/13#issuecomment-642486638

**Comment by yutasuzuki** [comment]
@phithu Thanks! Fix it in the next update!

**Comment by yutasuzuki** [comment]
@phithu The library has been updated.
Thank you!!
