### ISSUE TITLE
Not Working on both IOS/Android

### ISSUE THREAD

**Issue by ahsanparacha02** [yutasuzuki/react-native-record-screen#4]
when i start recording on android it automatically stop after sec and video not save on phone memory, and on ios side i got exception when i start recoding "Recording not active". 
please help me to fixed this issue

**Comment by EdsonMello-code** [comment]
@ahsanparacha02 I also had this problem.

**Comment by adeshpandey** [comment]
@yutasuzuki I wonder if you were able to make it work in your example app itself. I have tried multiple times with your example and with new project but no luck. In the android it stops just after starting and nothing works afterwards but in iOS it does not work at all.

**Comment by yutasuzuki** [comment]
May I check this?
- Is the version of react-native-record-screen 3.0?
- Device or emulator?
  (The emulator won't work on iOS. Android confirms that it works with Pixel 3a API 30).

The devices we've checked here are listed below.
- iPhone Xs (iOS 13.7)
- Pixel 4a (Android 10)

I only have an iPhone Xs and a Pixel 4a, so it may be difficult to solve this problem with other devices.

**Comment by Mopiiex20** [comment]
I test this lib on real devices with iOS 14 and it works fine :) But at the same time it doesn't work on simulators with different iOSs , I think it is because of permissions of recording screen that unavailable on simulators.

**Comment by yutasuzuki** [comment]
@Mopiiex20 I know that when I use the simulator, it stops with an error about the camera.
But if you turn off the camera's permission, it won't work as a module.
Therefore, the iOS simulator is not supported

I am not familiar with iOS development.
If you know how to get the camera to work in the simulator, please let me know.

**Comment by yutasuzuki** [comment]
If people want to use it in the iOS simulator, we'll create a new Issue.

**Comment by Mopiiex20** [comment]
@yutasuzuki Earlier I use [this](https://github.com/alskipp/ASScreenRecorder) lib to record screen , it record screen on simulators, and probably could help you to implement this feature , as addition this lib use scale factor of different devices to record screen more accurately.

**Comment by yutasuzuki** [comment]
@Mopiiex20 Thanks.
I tried ASScreenRecorder myself. With this library, when I left the video or camera playing, that part of the screen recording turned black.
That's why I made a react-native-record-screen using replaykit.

**Comment by Mopiiex20** [comment]
@yutasuzuki what about green [lines](https://prnt.sc/ur09d8) when save record ?

**Comment by yutasuzuki** [comment]
@Mopiiex20 I've created a new Issue, so let's talk about it there. #5

**Comment by adeshpandey** [comment]
@yutasuzuki I managed to run this on android with adding permission check for RECORD_AUDIO and by doing same on iOS as well.

**Comment by yutasuzuki** [comment]
@adeshpandey Good!

**Comment by yutasuzuki** [comment]
I close this Issue.
If there is a problem, open this issue again.
