### ISSUE TITLE
Not returning response while stopping record

### ISSUE THREAD

**Issue by emachalan-subramaniyan** [yutasuzuki/react-native-record-screen#6]
white i try to stop record screen no response return and also not saved on my device. 
am sorry for about my english.
please help me

**Comment by yutasuzuki** [comment]
@emachalan-subramaniyan 
I'm not good at english too. Don't worry it.

Tell your device information.
* iOS or Android
* version
* real device or Simulator
* device name (ex. iPhone 12, Pixel 5...)

if you have error log, write to this issue.

**Comment by emachalan-subramaniyan** [comment]
Android 
version 10
real device
vivo z1 pro

**Comment by yutasuzuki** [comment]
@emachalan-subramaniyan 
Sorry...I don't know that device.

This module dependent on the HBRecorder for Android.
Please check this issues. [HBRecorder Issue](https://github.com/HBiSoft/HBRecorder/issues?q=)

Or permmission?

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
<uses-permission android:name="android.permission.RECORD_AUDIO" />
<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
```

**Comment by emachalan-subramaniyan** [comment]
Now it's working. thank's for your response.

**Comment by mgpepe** [comment]
Hi, I have the same issue. 

STEPS:
I installed plugin as per instructions. 
I included all the permissions. 

I have the following code:
```
    const _handleOnRecording = async () => {
        
      if (recording) {
         
        setRecording(false);
        
        setRecording(false);
        const res = await RecordScreen.stopRecording().catch((error) =>
          console.warn(error)
        );
        
        console.warn('res', res);
        if (res) {
          setUri(res.result.outputURL);
        }
      } else {
        setUri('');
        setRecording(true);
        await RecordScreen.startRecording().catch((error) => {
          console.warn(error);
          setRecording(false);
          setUri('');
        });
        console.warn('done starting');
      }
    };
```

Expected results:
I would expect that when stopping, I would either get a console from error:
```
 const res = await RecordScreen.stopRecording().catch((error) =>
          console.warn(error)
        );
```

or I should get a console from success through this:
```
console.warn('res', res);
```

Actual results:
none of those two consoles appear. Seems to crash at `stopRecording`. 

Versions:
```
"react": "16.13.1",
"react-native": "0.63.3",
android 10
real phone - huawei p30 pro
```

Any advice @yutasuzuki? 
@emachalan-subramaniyan how did you solve it?

**Comment by yutasuzuki** [comment]
@mgpepe Do you see any errors in Android Studio's logcat?

**Comment by tmxiong** [comment]
use this, it work for me !
```
RecordScreen.stopRecording()
      .then(res => {
          console.log(res);
      })
      .catch((error) =>
      console.warn(error)
  );

  // or
  // try{
  //     const res = await RecordScreen.stopRecording()
  //     console.log(res);
  // }catch(error) {
  //     console.warn(error)
  // }

// this not return res for android!
// const res = await RecordScreen.stopRecording().catch((error) =>
//     console.warn(error)
// );
```

**Comment by AlejandroAguilar99** [comment]
> Hi, I have the same issue.
> 
> STEPS: I installed plugin as per instructions. I included all the permissions.
> 
> I have the following code:
> 
> ```
>     const _handleOnRecording = async () => {
>         
>       if (recording) {
>          
>         setRecording(false);
>         const res = await RecordScreen.stopRecording().catch((error) =>
>           console.warn(error)
>         );
>         
>         console.warn('res', res);
>         if (res) {
>           setUri(res.result.outputURL);
>         }
>       } else {
>         setUri('');
>         setRecording(true);
>         await RecordScreen.startRecording().catch((error) => {
>           console.warn(error);
>           setRecording(false);
>           setUri('');
>         });
>         console.warn('done starting');
>       }
>     };
> ```
> 
> Expected results: I would expect that when stopping, I would either get a console from error:
> 
> ```
>  const res = await RecordScreen.stopRecording().catch((error) =>
>           console.warn(error)
>         );
> ```
> 
> or I should get a console from success through this:
> 
> ```
> console.warn('res', res);
> ```
> 
> Actual results: none of those two consoles appear. Seems to crash at `stopRecording`.
> 
> Versions:
> 
> ```
> "react": "16.13.1",
> "react-native": "0.63.3",
> android 10
> real phone - huawei p30 pro
> ```
> 
> Any advice @yutasuzuki? @emachalan-subramaniyan how did you solve it?

hey bro! did you managed to make solve this?
