### ISSUE TITLE
App carashes when pressing the stop button from the foreground.

### ISSUE THREAD

**Issue by RAIERIN** [yutasuzuki/react-native-record-screen#79]
![Screenshot_1663061193](https://user-images.githubusercontent.com/56987934/189865335-9cf2d002-7f43-45f5-b05d-db766a91907d.png)
![Screen Shot 2022-09-13 at 3 12 07 PM](https://user-images.githubusercontent.com/56987934/189865406-98452a69-54b6-4407-90f9-92b212244f7d.png)

**Comment by fizawisedv** [comment]
I have the same issue. Did you find anything @RAIERIN?

**Comment by RAIERIN** [comment]
You can use this package: https://github.com/umbertoghio/react-native-screen-mic-recorder

**Comment by alihaxan020** [comment]
@robrechtme 
**HELP!**
How implement to stop recording from foreground?

**Comment by robrechtme** [comment]
@alihaxan020 please don’t tag me for messages like this 😕 I’ve opened a PR which fixes the bug, but this needs to be merged by a maintainer (not me). See #86
