### ISSUE TITLE
Question: Do we need to install separately HBRecorder?

### ISSUE THREAD

**Issue by mgpepe** [yutasuzuki/react-native-record-screen#8]
I am slightly confused from the documentation - does it say that it uses HBR or that I need to install it myself as a prerequisite?

**Comment by yutasuzuki** [comment]
@mgpepe 
You do not need to install HBRecorder.
The implementation depends on HBRecorder as a description.

I'm sorry if this is confusing.

**Comment by mgpepe** [comment]
Thanks!
