### ISSUE TITLE
Is it possible to record the screen on iOS outside of the app?

### ISSUE THREAD

**Issue by TeodoraD** [yutasuzuki/react-native-record-screen#9]
On Android it is working but it throws an error when trying it on iOS.
Steps:
1. Start recording
2. Close the app to the background
3. Return to the app and stop recording

Error:
Possible Unhandled Promise Rejection (id: 0):
Error: The operation couldn’t be completed. (Cocoa error -1.)
promiseMethodWrapper@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:2275:45
_handleOnRecording$@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:113849:41
tryCatch@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:28643:23
invoke@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:28816:32
tryCatch@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:28643:23
invoke@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:28716:30
http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:28726:21
tryCallOne@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:3475:16
http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:3576:27
_callTimer@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:30664:17
_callImmediatesPass@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:30703:17
callImmediates@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:30920:33
__callImmediates@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:2769:35
http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:2555:34
__guard@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:2752:15
flushedQueue@http://192.168.100.3:8081/index.bundle?platform=ios&dev=true&minify=false:2554:21
flushedQueue@[native code]
invokeCallbackAndReturnFlushedQueue@[native code]

**Comment by yutasuzuki** [comment]
@TeodoraD 
It does not support recording other than your own app.

You can do that by using Replaykit2. 
https://stackoverflow.com/questions/54480680/use-replaykit-to-record-any-app-on-screen

Sorry, but there are no plans for this module to support it.

**Comment by TeodoraD** [comment]
Thanks!
